/************************************************************************
  This software is subject to the terms of the IBM alphaBeans with Source 
  License Agreement available at 
  www.software.ibm.com/developer/alphabeans/source/license.html.
  
  Copyright (c) 1999 IBM Corporation and others. All rights reserved. 
  
  You must accept the terms of that agreement to use this software.
 *************************************************************************/

package com.ibm.network.ftp.ui;

/**
 * This class was generated by a SmartGuide.
 * 
 */
class CommandInterpreter {
	// private String command;
	private FTPUI myParent;

	/**
	 * This method was created by a SmartGuide.
	 * 
	 * @param container
	 *            FTPUI.FTPUIBean
	 */
	public CommandInterpreter(FTPUI container) {
		this.myParent = container;
	}

	/**
	 * This method was created by a SmartGuide.
	 * 
	 * @param ae
	 *            java.awt.event.ActionEvent
	 */
	public void executeCommand(java.awt.event.ActionEvent ae) {
		// Get the source of the command
		String actCommand = ae.getActionCommand();
		String source = actCommand.trim();

		// Call the corresponding method in parent
		if (source.equalsIgnoreCase("connect")) {
			myParent.connect();
		} else if (source.equalsIgnoreCase("disconnect")
				|| source.equalsIgnoreCase("disconn")) {
			myParent.disconnect();
		} else if (source.equalsIgnoreCase("get")
				|| source.equalsIgnoreCase("getfile")) {
			myParent.download();
		} else if (source.equalsIgnoreCase("put")
				|| source.equalsIgnoreCase("putfile")) {
			myParent.upload();
		} else if (source.equalsIgnoreCase("rename")) {
			myParent.rename();
		} else if (source.equalsIgnoreCase("deleteFile")
				|| source.equalsIgnoreCase("delete")) {
			// For both file & directory deletion
			myParent.deleteFile();
		} else if (source.equalsIgnoreCase("removeDir")
				|| source.equalsIgnoreCase("rmDir")) {
			myParent.removeDir();
		} else if (source.equalsIgnoreCase("makeDir")
				|| source.equalsIgnoreCase("MkDir")) {
			myParent.makeDir();
		} else if (source.equalsIgnoreCase("changeDir")
				|| source.equalsIgnoreCase("chDir")) {
			myParent.changeDir();
		} else if (source.equalsIgnoreCase("abort")) {
			myParent.abort();
		} else if (source.equalsIgnoreCase("getStatus")) {
			myParent.checkStatus();
		} else if (source.equalsIgnoreCase("changeFocus")) {
			myParent.changeFocus();
		} else if (source.equalsIgnoreCase("clearStatus")
				|| source.equalsIgnoreCase("clearstat")) {
			myParent.clearStatusWindow();
		} else if (source.equalsIgnoreCase("configureSocks")) {
			myParent.configureSocks();
		}
		return;
	}
}
