/************************************************************************
  This software is subject to the terms of the IBM alphaBeans with Source 
  License Agreement available at 
  www.software.ibm.com/developer/alphabeans/source/license.html.
  
  Copyright (c) 1999 IBM Corporation and others. All rights reserved. 
  
  You must accept the terms of that agreement to use this software.
*************************************************************************/
  
package com.ibm.network.ftp.ui;
/**
 * This interface was generated by a SmartGuide.
 * 
 */
 interface ConnectDialogInterface {
/**
 * This method was created by a SmartGuide.
 * @param hostName java.lang.String
 * @param userName java.lang.String
 * @param password java.lang.String
 * @param account java.lang.String
 */
 public void messageConnectDialog (String hostName,String userName,String password,String account );         
}
