/************************************************************************
  This software is subject to the terms of the IBM alphaBeans with Source 
  License Agreement available at 
  www.software.ibm.com/developer/alphabeans/source/license.html.
  
  Copyright (c) 1999 IBM Corporation and others. All rights reserved. 
  
  You must accept the terms of that agreement to use this software.
*************************************************************************/
  
package com.ibm.network.ftp.ui;
/**
 * This interface was generated by a SmartGuide.
 * 
 */
 interface SocksDialogInterface {
/**
 * This method was created by a SmartGuide.
 * @param socksHost java.lang.String
 * @param socksPort int
 */
public void setSocksInfo (String socksHost,String socksPort );
}
