/************************************************************************
  This software is subject to the terms of the IBM alphaBeans with Source 
  License Agreement available at 
  www.software.ibm.com/developer/alphabeans/source/license.html.
  
  Copyright (c) 1999 IBM Corporation and others. All rights reserved. 
  
  You must accept the terms of that agreement to use this software.
*************************************************************************/
  
package com.ibm.network.ftp.protocol;
/**
 * This class was generated by a SmartGuide.
 * 
 */
class FtpDirectory {
	private String dirName;
	private Protocol protocol;
/**
 * This method was created by a SmartGuide.
 * @param dirName java.lang.String
 * @param protocol FTPProtocolBean.Protocol
 */
public FtpDirectory ( String dirName,Protocol protocol) {
	this.dirName=dirName;
	this.protocol=protocol;
}
/**
 * This method was created by a SmartGuide.
 */
public void changeDir ( ) {
	//check that both protocol and dirname are not null
	if(protocol!=null && this.dirName!=null){
		protocol.changeDir(this.dirName);
	}	
	return;
}
/**
 * This method was created by a SmartGuide.
 */
public void makeDir() {
	//check that both protocol and dirname are not null
	if(protocol!=null && this.dirName!=null){
		protocol.makeDir(this.dirName);
	}	
	return;
}
/**
 * This method was created by a SmartGuide.
 */
public void removeDir( ) {
	//check that both protocol and dirname are not null
	if(protocol!=null && this.dirName!=null){
		protocol.deleteDir(this.dirName);
	}	
	return;
}
}
