/************************************************************************
  This software is subject to the terms of the IBM alphaBeans with Source 
  License Agreement available at 
  www.software.ibm.com/developer/alphabeans/source/license.html.
  
  Copyright (c) 1999 IBM Corporation and others. All rights reserved. 
  
  You must accept the terms of that agreement to use this software.
*************************************************************************/
  
package com.ibm.network.ftp.protocol;

import com.ibm.network.ftp.FileInfo;

/**
 * This class was generated by a SmartGuide.
 * 
 */
abstract class Protocol {
	//private   String currentDir;
/**
 * This method was created by a SmartGuide.
 * @param newDir java.lang.String
 */
public abstract void changeDir ( java.lang.String newDir); 
/**
 * This method was created by a SmartGuide.
 * @param dirName java.lang.String
 */
public abstract void deleteDir (java.lang.String dirName ); 
/**
 * This method was created by a SmartGuide.
 * @param fileName java.lang.String
 */
public abstract void deleteFile (java.lang.String fileName ) ;
/**
 * This method was created by a SmartGuide.
 * @return java.util.Vector
 */
public abstract java.util.Vector<FileInfo> fileList ( ) ;
/**
 * This method was created by a SmartGuide.
 * @return java.lang.String
 */
public abstract java.lang.String getCurrentDir();
/**
 * This method was created by a SmartGuide.
 * @param dirName java.lang.String
 */
public abstract void makeDir(java.lang.String dirName) ;
/**
 * This method was created by a SmartGuide.
 * @param text java.lang.String
 */
protected abstract void printText (java.lang.String text ); 
/**
 * This method was created by a SmartGuide.
 * @param oldName java.lang.String
 * @param newName java.lang.String
 */
public abstract void rename (java.lang.String oldName, java.lang.String newName ); 
}
